# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: CI
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      max-parallel: 32

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: test-cases/integration-test.sh
